Task-57126: Fix explicit type casting problem caused by select SOC_METADATA_ITEMS query with postgreSQL (#107)
Prior to this change, an exception:

> org.hibernate.exception.SQLGrammarException: could not extract ResultSet 
  Caused by: org.postgresql.util.PSQLException: ERROR: operator does not exist: bigint = character varying
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.

occurs when the PublishedNewsDisplayedPropUpgrade is executed in postgreSQL instances which causes an explicit type casting problem between METADATA_ID field and values used by the where condition of the select SOC_METADATA_ITEMS_PROPERTIES query. After this fix, we ensure the implicit casting between METADATA_ID field type and the values used in the where condition.